#!/usr/bin/env bash
# SubDeck installer / updater.
# Usage: ./install.sh [--tool claude|codex|copilot|cursor|antigravity|opencode] [--uninstall] [--hooks]
#   claude (default): talks to the claude CLI only (marketplace add/update + plugin install/update).
#   codex:   copies the SubDeck agents as Codex custom-agent TOML to ${CODEX_HOME:-~/.codex}/agents
#            (plugins cannot bundle agents). Install the plugin itself with the two codex commands it prints.
#   cursor:  copies a self-contained plugin (.cursor-plugin + portable skills + scripts) to ${CURSOR_HOME:-~/.cursor}/plugins/local/subdeck.
#   antigravity: assembles plugin.json + skills + agents + rules + scripts in ${SUBDECK_ANTIGRAVITY_DIR:-~/.subdeck/antigravity-plugin} and runs "agy plugin install" on it when agy is present.
#   opencode: copies subdeck.js + 3 commands into ${OPENCODE_CONFIG_HOME:-~/.config/opencode} and a plugin copy to ${SUBDECK_PLUGIN_COPY:-~/.subdeck/plugin}; prints the opencode.json instructions line.
#   copilot: fallback for what the plugin does not deliver: copies the agents as <name>.agent.md to
#            ${COPILOT_HOME:-~/.copilot}/agents; with --hooks also writes ${COPILOT_HOME:-~/.copilot}/hooks/subdeck.json
#            pointing at this clone's scripts (only if the plugin's own hooks do not fire; both together run twice).
# Files written for codex/copilot carry a "managed by SubDeck" marker; --uninstall removes only those,
# and an existing foreign file of the same name is never overwritten. Never edits settings files, no sudo.
set -u
REPO="emiirhandemirci/SubDeck"
MKT="subdeck"
PLUGIN="subdeck@subdeck"
HERE="$(cd "$(dirname "$0")" && pwd)"
TOOL=claude; UNINSTALL=0; WITHHOOKS=0
while [ $# -gt 0 ]; do
  case "$1" in
    --uninstall) UNINSTALL=1 ;;
    --hooks) WITHHOOKS=1 ;;
    --tool) shift; TOOL="${1:-}" ;;
    --tool=*) TOOL="${1#--tool=}" ;;
    *) echo "Unknown argument: $1" >&2; echo "Usage: ./install.sh [--tool claude|codex|copilot|cursor|antigravity|opencode] [--uninstall] [--hooks]" >&2; exit 2 ;;
  esac
  shift
done
case "$TOOL" in claude|codex|copilot|cursor|antigravity|opencode) ;; *) echo "Unknown tool: $TOOL (use claude, codex, copilot, cursor, antigravity or opencode)" >&2; exit 2 ;; esac

MARK="managed by SubDeck install script"
AGENT_DIR="$HERE/plugins/subdeck/agents"

# fm FILE KEY: value of a frontmatter key (first block only)
fm() { awk -v k="$2" '/^---\r?$/{c++; next} c==1 { sub(/\r$/,""); i=index($0,":"); if (i>0 && substr($0,1,i-1)==k) { v=substr($0,i+1); sub(/^[ \t]+/,"",v); print v; exit } }' "$1"; }
body() { awk 'c>=2{sub(/\r$/,""); print} /^---\r?$/{c++}' "$1"; }
qesc() { local s="${1//\\/\\\\}"; printf '%s' "${s//\"/\\\"}"; }
# owned FILE: true when absent or carrying the marker
owned() { [ ! -e "$1" ] || grep -q "$MARK" "$1" 2>/dev/null; }

agent_names() { local f; for f in "$AGENT_DIR"/*.md; do basename "$f" .md; done; }

write_codex_agent() { # name -> TOML
  local n="$1" src="$AGENT_DIR/$1.md" out="$2/$1.toml" desc model effort tools
  desc="$(fm "$src" description)"; model="$(fm "$src" model)"; effort="$(fm "$src" effort)"; tools="$(fm "$src" tools)"
  # Claude model aliases (sonnet/opus/inherit) mean nothing to Codex: leave "model" out so Codex uses its own default.
  [ "$model" = opus ] && effort=high
  case "$effort" in low|medium|high) ;; *) effort="" ;; esac
  owned "$out" || { echo "skip $out (not managed by SubDeck)"; return 0; }
  {
    echo "# $MARK; do not edit (re-run install.sh --tool codex to refresh)"
    echo "name = \"$n\""
    echo "description = \"$(qesc "$desc")\""
    [ -n "$effort" ] && echo "model_reasoning_effort = \"$effort\""
    # a read-only Claude agent (tools: Read, Grep, Glob only) maps to a read-only sandbox
    if [ -n "$tools" ] && ! printf '%s' "$tools" | grep -qE 'Bash|Write|Edit'; then echo 'sandbox_mode = "read-only"'; fi
    echo "developer_instructions = '''"
    body "$src"
    echo "'''"
  } > "$out"
  echo "wrote $out"
}

# Copilot agents are generated by plugins/subdeck/scripts/build-portable.sh and committed; copy them.
copy_copilot_agent() {
  local src="$HERE/plugins/subdeck/.github/agents/$1.agent.md" out="$2/$1.agent.md"
  [ -f "$src" ] || { echo "missing $src (run plugins/subdeck/scripts/build-portable.sh)" >&2; return 1; }
  owned "$out" || { echo "skip $out (not managed by SubDeck)"; return 0; }
  cp "$src" "$out" && echo "wrote $out"
}

# Cursor and Antigravity: assemble a self-contained plugin directory from the committed (generated) files.
if [ "$TOOL" = cursor ] || [ "$TOOL" = antigravity ]; then
  PL="$HERE/plugins/subdeck"
  if [ "$TOOL" = cursor ]; then
    DEST="${CURSOR_HOME:-$HOME/.cursor}/plugins/local/subdeck"; SRCCHK="$HERE/.cursor-plugin/plugin.json"
  else
    DEST="${SUBDECK_ANTIGRAVITY_DIR:-$HOME/.subdeck/antigravity-plugin}"; SRCCHK="$PL/.antigravity/plugin.json"
  fi
  if [ "$UNINSTALL" = 1 ]; then
    if [ -f "$DEST/.subdeck-managed" ]; then rm -rf "$DEST"; echo "removed $DEST"; else echo "nothing to remove at $DEST"; fi
    [ "$TOOL" = antigravity ] && echo "Also run: agy plugin uninstall subdeck"
    exit 0
  fi
  [ -f "$SRCCHK" ] || { echo "missing $SRCCHK (run from a SubDeck clone; plugins/subdeck/scripts/build-portable.sh regenerates it)" >&2; exit 1; }
  if [ -e "$DEST" ] && [ ! -f "$DEST/.subdeck-managed" ]; then echo "skip $DEST (exists and is not managed by SubDeck)"; exit 0; fi
  rm -rf "$DEST"; mkdir -p "$DEST" || exit 1
  if [ "$TOOL" = cursor ]; then
    cp -R "$HERE/.cursor-plugin" "$DEST/.cursor-plugin" && mkdir -p "$DEST/plugins/subdeck" \
      && cp -R "$PL/skills-portable" "$PL/scripts" "$DEST/plugins/subdeck/" || exit 1
  else
    cp -R "$PL/.antigravity/." "$DEST/" && cp -R "$PL/scripts" "$DEST/scripts" || exit 1
  fi
  echo "$MARK" > "$DEST/.subdeck-managed"
  echo "wrote $DEST"
  echo
  if [ "$TOOL" = cursor ]; then
    echo "Restart Cursor or run 'Developer: Reload Window'; SubDeck appears under Customize. Skills, sub-agents and the rulebook rule are loaded; guard and logging hooks are not shipped for Cursor."
  else
    AGY="$(command -v agy 2>/dev/null || true)"
    if [ -n "$AGY" ]; then "$AGY" plugin install "$DEST" || echo "agy plugin install failed; run it yourself: agy plugin install \"$DEST\""
    else echo "Antigravity CLI (agy) not found. Install the plugin with: agy plugin install \"$DEST\""; fi
    echo "Guard and logging hooks are not shipped for Antigravity. Gemini CLI users: gemini extensions install https://github.com/$REPO"
  fi
  exit 0
fi

# OpenCode: local JS plugin + commands under the OpenCode config dir, scripts in a private copy of the plugin directory.
if [ "$TOOL" = opencode ]; then
  PL="$HERE/plugins/subdeck"
  OC="${OPENCODE_CONFIG_HOME:-$HOME/.config/opencode}"
  COPY="${SUBDECK_PLUGIN_COPY:-$HOME/.subdeck/plugin}"
  if [ "$UNINSTALL" = 1 ]; then
    if [ -f "$COPY/.subdeck-managed" ]; then
      rm -f "$OC/plugins/subdeck.js" "$OC/commands/subdeck-status.md" "$OC/commands/subdeck-settings.md" "$OC/commands/subdeck-desk.md"
      rm -rf "$COPY"; echo "removed OpenCode plugin, commands and $COPY"
    else echo "nothing to remove (no SubDeck copy at $COPY)"; fi
    echo "If you added SubDeck to the \"instructions\" array in opencode.json, remove that entry yourself."
    exit 0
  fi
  [ -f "$PL/opencode/subdeck.js" ] || { echo "missing $PL/opencode/subdeck.js (run from a SubDeck clone)" >&2; exit 1; }
  if [ -e "$COPY" ] && [ ! -f "$COPY/.subdeck-managed" ]; then echo "skip $COPY (exists and is not managed by SubDeck)"; exit 0; fi
  if [ ! -f "$COPY/.subdeck-managed" ] && { [ -e "$OC/plugins/subdeck.js" ] || [ -e "$OC/commands/subdeck-status.md" ]; }; then echo "skip: $OC already has a subdeck plugin or command that SubDeck did not write"; exit 0; fi
  mkdir -p "$OC/plugins" "$OC/commands" "$(dirname "$COPY")" || exit 1
  rm -rf "$COPY"; cp -R "$PL" "$COPY" || exit 1
  rm -rf "$COPY/tests"
  echo "$MARK" > "$COPY/.subdeck-managed"
  cp "$PL/opencode/subdeck.js" "$OC/plugins/subdeck.js" && cp "$PL"/opencode/commands/*.md "$OC/commands/" || exit 1
  echo "wrote $OC/plugins/subdeck.js, three commands in $OC/commands, and $COPY"
  echo
  echo "Rulebook: add this to $OC/opencode.json yourself (the installer never edits settings files):"
  echo "  {\"instructions\": [\"$COPY/skills/orchestrator/SKILL.md\"]}"
  echo "Needs bash (Git Bash on Windows). Restart OpenCode. Commands: /subdeck-status, /subdeck-settings, /subdeck-desk."
  exit 0
fi

if [ "$TOOL" = codex ] || [ "$TOOL" = copilot ]; then
  if [ "$TOOL" = codex ]; then BASE="${CODEX_HOME:-$HOME/.codex}"; EXT=toml; else BASE="${COPILOT_HOME:-$HOME/.copilot}"; EXT=agent.md; fi
  ADIR="$BASE/agents"
  if [ "$UNINSTALL" = 1 ]; then
    n=0
    for a in $(agent_names); do
      f="$ADIR/$a.$EXT"
      if [ -e "$f" ] && grep -q "$MARK" "$f" 2>/dev/null; then rm -f "$f"; echo "removed $f"; n=$((n+1)); fi
    done
    if [ "$TOOL" = copilot ] && [ -e "$BASE/hooks/subdeck.json" ] && grep -q SUBDECK_TOOL "$BASE/hooks/subdeck.json" 2>/dev/null; then
      rm -f "$BASE/hooks/subdeck.json"; echo "removed $BASE/hooks/subdeck.json"; n=$((n+1))
    fi
    echo "SubDeck $TOOL files removed: $n. Remove the plugin itself with: $TOOL plugin $([ "$TOOL" = codex ] && echo remove || echo uninstall) $PLUGIN"
    exit 0
  fi
  [ -d "$AGENT_DIR" ] || { echo "Agent sources not found at $AGENT_DIR (run from a SubDeck clone)." >&2; exit 1; }
  mkdir -p "$ADIR" || exit 1
  for a in $(agent_names); do
    if [ "$TOOL" = codex ]; then write_codex_agent "$a" "$ADIR"; else copy_copilot_agent "$a" "$ADIR"; fi
  done
  if [ "$TOOL" = copilot ] && [ "$WITHHOOKS" = 1 ]; then
    ROOT="$HERE/plugins/subdeck"
    command -v cygpath >/dev/null 2>&1 && ROOT="$(cygpath -m "$ROOT")"
    mkdir -p "$BASE/hooks" || exit 1
    HF="$BASE/hooks/subdeck.json"
    if [ -e "$HF" ] && ! grep -q SUBDECK_TOOL "$HF" 2>/dev/null; then
      echo "skip $HF (not managed by SubDeck)"
    else
      sed "s#__ROOT__#$ROOT#g" "$HERE/plugins/subdeck/hooks/copilot-hooks.json" > "$HF" && echo "wrote $HF"
    fi
  fi
  echo
  if [ "$TOOL" = codex ]; then
    echo "Now install the plugin (skills + hooks): codex plugin marketplace add $REPO && codex plugin add $PLUGIN"
    echo "Codex asks you to review and trust the hooks on first use. Restart Codex afterwards."
  else
    echo "Now install the plugin (skills, hooks, agents): copilot plugin marketplace add $REPO && copilot plugin install $PLUGIN"
    echo "Hooks come from the plugin; add --hooks here only if they do not fire (that file runs this clone's scripts, so keep the clone). Restart Copilot afterwards."
  fi
  exit 0
fi

CLAUDE="$(command -v claude 2>/dev/null || true)"
if [ -z "$CLAUDE" ]; then
  for c in "$HOME/.local/bin/claude" "$HOME/.local/bin/claude.exe"; do
    [ -x "$c" ] && { CLAUDE="$c"; break; }
  done
fi
if [ -z "$CLAUDE" ]; then
  echo "Claude Code CLI not found." >&2
  echo "Install Claude Code first: https://docs.claude.com/en/docs/claude-code/setup" >&2
  exit 1
fi

if [ "$UNINSTALL" = 1 ]; then
  "$CLAUDE" plugin uninstall "$PLUGIN" || exit 1
  "$CLAUDE" plugin marketplace remove "$MKT" || exit 1
  echo "SubDeck uninstalled. Restart Claude Code."
  exit 0
fi

if "$CLAUDE" plugin marketplace list 2>/dev/null | grep -qw "$MKT"; then
  echo "SubDeck marketplace found; updating."
  "$CLAUDE" plugin marketplace update "$MKT" || exit 1
  "$CLAUDE" plugin update "$PLUGIN" || exit 1
else
  "$CLAUDE" plugin marketplace add "$REPO" || exit 1
  "$CLAUDE" plugin install "$PLUGIN" || exit 1
fi

echo
"$CLAUDE" plugin list 2>/dev/null | grep -i -A3 "subdeck" | head -5
echo
echo "Restart Claude Code to load the plugin (in a running session, /reload-plugins also works; until then subdeck agent types may be reported missing)."
echo "Then try /subdeck:status, or start the dashboard with /subdeck:desk."
