#!/usr/bin/env bash
# Deterministic pre-push facts for /subdeck:pr. Always exits 0.
# Usage: bash pr-facts.sh [repo-dir]
DIR="${1:-.}"
cd "$DIR" 2>/dev/null || { echo "not a directory: $DIR"; exit 0; }
if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  echo "not a git repository"; exit 0
fi

echo "== branch =="
BR="$(git branch --show-current 2>/dev/null)"
echo "${BR:-(detached HEAD)}"

echo "== upstream =="
UP="$(git rev-parse --abbrev-ref --symbolic-full-name '@{u}' 2>/dev/null)"
if [ -n "$UP" ]; then
  RANGE="@{u}..HEAD"; echo "$UP"
else
  RANGE="HEAD"; echo "(none; showing all commits on HEAD, max 50)"
fi

echo "== status (porcelain) =="
ST="$(git status --porcelain 2>/dev/null)"
if [ -n "$ST" ]; then echo "$ST"; else echo "(clean)"; fi

echo "== commits to push =="
LOG="$(git log --oneline -n 50 $RANGE 2>/dev/null)"
if [ -n "$LOG" ]; then echo "$LOG"; else echo "(none)"; fi

echo "== attribution scan =="
HITS=""
for h in $(git log --format=%H -n 50 $RANGE 2>/dev/null); do
  if git log -1 --format=%B "$h" 2>/dev/null | grep -i -q -E 'co-authored-by|generated with|generated by'; then
    HITS="$HITS$(git log -1 --format='%h %s' "$h")"$'\n'
  fi
done
if [ -n "$HITS" ]; then printf 'ATTRIBUTION FOUND in:\n%s' "$HITS"; else echo "(no attribution lines)"; fi

echo "== diff stat =="
if [ -n "$UP" ]; then
  DS="$(git diff --stat "@{u}..HEAD" 2>/dev/null)"
else
  DS="$(git diff --stat "$(git hash-object -t tree /dev/null)" HEAD 2>/dev/null | tail -n 1)"
fi
if [ -n "$DS" ]; then echo "$DS"; else echo "(none)"; fi
exit 0
